/*
 * Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
 * 
 * On Sat Jun 14 19:50:45 IST 2025
 * 
 */

/* Generation options: keep-fires */
#ifndef __model_mkMouse_h__
#define __model_mkMouse_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkMouse.h"

/* Class declaration for a model of mkMouse */
class MODEL_mkMouse : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkMouse *mkMouse_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkMouse();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(char const **name, char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkMouse();
}

#endif /* ifndef __model_mkMouse_h__ */
